In [5]:
import torch
import numpy as np
import pandas as pd

In [9]:
b = torch.tensor([[3.],[4.]])
d = b.detach().numpy()
d

array([[3.],
       [4.]], dtype=float32)

In [32]:
x = torch.tensor(2., requires_grad=True)
y = x ** 2
y.backward()
print(x.grad)
# x.grad.zero_()
z = x + 3
z.backward()
print(x.grad)
x.grad.zero_()
print(x.grad)

tensor(4.)
tensor(1.)
tensor(0.)

In [6]:
target = torch.tensor([[3.],[4.]])
print(target)

tensor([[3.],
        [4.]])

In [38]:
target_ = target.view(1, -1)
print(target_)

tensor([[3.],
        [4.]])

In [49]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
train_data = pd.read_csv("wine_train.csv")
test_data  = pd.read_csv('wine_test.csv')
train_data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.353982,0.239726,0.27,0.095890,0.071906,0.183099,0.077739,0.373715,0.346457,0.281437,0.430769,0.4
1,0.176991,0.503425,0.02,0.102740,0.083612,0.197183,0.060071,0.455213,0.629921,0.161677,0.400000,0.6
2,0.522124,0.082192,0.47,0.082192,0.090301,0.070423,0.063604,0.567548,0.322835,0.341317,0.400000,0.8
3,0.327434,0.345890,0.20,0.041096,0.113712,0.366197,0.399293,0.523495,0.330709,0.473054,0.107692,0.2
4,0.477876,0.198630,0.45,0.363014,0.098662,0.070423,0.028269,0.510279,0.370079,0.095808,0.523077,0.8

In [9]:
train_data.iloc[:,0:11]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,0.353982,0.239726,0.27,0.095890,0.071906,0.183099,0.077739,0.373715,0.346457,0.281437,0.430769
1,0.176991,0.503425,0.02,0.102740,0.083612,0.197183,0.060071,0.455213,0.629921,0.161677,0.400000
2,0.522124,0.082192,0.47,0.082192,0.090301,0.070423,0.063604,0.567548,0.322835,0.341317,0.400000
3,0.327434,0.345890,0.20,0.041096,0.113712,0.366197,0.399293,0.523495,0.330709,0.473054,0.107692
4,0.477876,0.198630,0.45,0.363014,0.098662,0.070423,0.028269,0.510279,0.370079,0.095808,0.523077
...,...,...,...,...,...,...,...,...,...,...,...
1274,0.318584,0.452055,0.00,0.089041,0.128763,0.169014,0.070671,0.567548,0.496063,0.077844,0.184615
1275,0.380531,0.493151,0.34,0.034247,0.063545,0.042254,0.014134,0.401615,0.299213,0.089820,0.107692
1276,0.230088,0.308219,0.05,0.095890,0.115385,0.211268,0.106007,0.408957,0.503937,0.161677,0.292308
1277,0.283186,0.308219,0.31,0.061644,0.095318,0.352113,0.402827,0.453744,0.433071,0.119760,0.138462
1278,0.194690,0.383562,0.21,0.082192,0.096990,0.112676,0.060071,0.395742,0.503937,0.161677,0.292308

In [17]:
s = train_data.sample(frac=0.1,axis=0)
s

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
72,0.203540,0.191781,0.14,0.102740,0.122074,0.281690,0.120141,0.494126,0.543307,0.179641,0.200000,0.6
1132,0.327434,0.407534,0.15,0.061644,0.128763,0.126761,0.162544,0.494126,0.385827,0.263473,0.169231,0.4
1030,0.318584,0.150685,0.37,0.068493,0.075251,0.591549,0.240283,0.294420,0.385827,0.287425,0.553846,0.6
413,0.106195,0.383562,0.02,0.061644,0.125418,0.281690,0.310954,0.317915,0.629921,0.113772,0.246154,0.4
919,0.353982,0.352740,0.68,0.061644,0.653846,0.253521,0.176678,0.458884,0.220472,0.491018,0.138462,0.4
...,...,...,...,...,...,...,...,...,...,...,...,...
1157,0.283186,0.280822,0.33,0.102740,0.113712,0.323944,0.487633,0.475771,0.440945,0.161677,0.169231,0.4
651,0.513274,0.198630,0.55,0.157534,0.107023,0.295775,0.169611,0.699706,0.322835,0.335329,0.230769,0.6
454,0.539823,0.191781,0.37,0.068493,0.115385,0.225352,0.081272,0.489721,0.299213,0.191617,0.430769,0.6
292,0.513274,0.219178,0.42,0.041096,0.222408,0.464789,0.148410,0.605727,0.503937,0.317365,0.230769,0.0
1248,0.292035,0.390411,0.21,0.082192,0.113712,0.450704,0.477032,0.450073,0.401575,0.107784,0.230769,0.4

In [12]:
test_data

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0.250000,0.454545,0.000000,0.079365,0.093489,0.169811,0.119718,0.421053,0.611765,0.270492,0.442308,0.6
1,0.113636,0.173554,0.421053,0.928571,0.070117,0.094340,0.746479,0.431239,0.470588,0.139344,0.519231,0.2
2,0.340909,0.247934,0.223684,0.063492,0.101836,0.094340,0.077465,0.556876,0.458824,0.180328,0.076923,0.6
3,0.215909,0.371901,0.000000,0.126984,0.115192,0.377358,0.239437,0.385399,0.600000,0.106557,0.384615,0.4
4,0.534091,0.144628,0.526316,0.023810,0.101836,0.245283,0.098592,0.417657,0.282353,0.098361,0.403846,0.6
...,...,...,...,...,...,...,...,...,...,...,...,...
315,0.397727,0.206612,0.421053,0.047619,0.090150,0.471698,0.309859,0.332767,0.564706,0.270492,0.576923,0.6
316,0.602273,0.338843,0.631579,0.103175,0.085142,0.094340,0.126761,0.777589,0.258824,0.163934,0.096154,0.6
317,0.875000,0.396694,0.855263,0.087302,0.085142,0.094340,0.126761,0.769100,0.152941,0.147541,0.211538,0.4
318,0.204545,0.586777,0.118421,0.047619,0.103506,0.056604,0.126761,0.398981,0.564706,0.049180,0.153846,0.4
319,0.170455,0.409091,0.000000,0.055556,0.088481,0.150943,0.077465,0.556876,0.658824,0.213115,0.076923,0.4

In [15]:

torch.tensor(test_data.values)

tensor([[0.2500, 0.4545, 0.0000,  ..., 0.2705, 0.4423, 0.6000],
        [0.1136, 0.1736, 0.4211,  ..., 0.1393, 0.5192, 0.2000],
        [0.3409, 0.2479, 0.2237,  ..., 0.1803, 0.0769, 0.6000],
        ...,
        [0.8750, 0.3967, 0.8553,  ..., 0.1475, 0.2115, 0.4000],
        [0.2045, 0.5868, 0.1184,  ..., 0.0492, 0.1538, 0.4000],
        [0.1705, 0.4091, 0.0000,  ..., 0.2131, 0.0769, 0.4000]],
       dtype=torch.float64)